---
title: "Proposed tutorials and people in each"
output: github_document
---

Below is a list of proposed topics for tutorials, and of people interested in each (so far). If you want to propose or join a tutorial, follow [this issue](https://github.com/forestgeo/forum/issues/2) or email maurolepore@gmail.com.





# GitHub tutorials

Aiming to audiences of 3 levels, I plan 3 tutorials.



## Participants so far

1. Alvaro Javier Duque Montoya, ajduque@unal.edu.co
1. Jie Yang, yangjie@xtbg.org.cn
1. Mei Qiming, qmei4597@scbg.ac.cn
1. YunFei Diao, diaoyunfei@126.com
1. Natalia Umaña, maumana@gmail.com
1. Andrew Quebbeman awq2101@columbia.edu
1. Helene Muller-Landau, hmullerlandau@gmail.com (1-2)
1. Sabrina Russo, srusso2@unl.edu (1-2)
1. YueHua HU, huyuehua@xtbg.org.cn (1-2)
1. Mohizah Bt. Mohamad, mohizahm@sarawak.gov.my (1-2)
1. Renato Valencia, renatovalenciar@gmail.com (1-2)
1. Musalmah (1-2)
1. Yao (1-2)
1. Yu Zhu, orienton2006@163.com (1-2)
1. Jenny Zambrano jzambrano@sesync.org (1-2)
1. @hqzzlo (1-2)
1. @matthewluskin
1. @jameshogan
1. @jonamyers
1. @rutujaCT
1. @iverenabiem
1. @teixeirak (2-3)
1. @djj4tree (2-3)
1. @JessieN (2-3)
1. @ljvrodriguez (2)
1. @ervanSTRI (1-3)

(Numbers mean the range of levels someone may be interested)



## GitHub tutorial 1: Installing the software to use GitHub from RStudio.

What date and time you prefer? https://goo.gl/B2yBq6

This tutorial is for those that want to install or configure the software during the tutorial (this is painful and time consuming). 

Contents: This is a good guide for what contents we will cover: http://happygitwithr.com/

> Getting all the necessary software installed, configured, and playing nicely together is honestly half the battle here. Brace yourself for some pain. The upside is that you can give yourself a pat on the back once you get through this. And you WILL get through this.

--http://happygitwithr.com/installation-pain.html



## GitHub tutorial 2: Using GitHub from RStudio

What day and time you prefer? https://goo.gl/KJmtR7

This tutorial is for those with a GitHub account, that have already installed Git (Git is the engine of GitHub), R and RStudio; these people configured it all but haven't fully incorporated these tools into their workflow.

Contents: These are good guide for what contents we may cover: 
- http://r-pkgs.had.co.nz/git.html.
- http://happygitwithr.com/

## GitHub tutorial 3: Using git beyond RStudio; the GitHub Work Flow, with master and issue-branches

What day and time you prefer? https://goo.gl/HEooiw

This tutorial is for those that use GitHub but want to use branches and Git from a shell to get more power.

Contents: I will cover the GitHub workflow: https://goo.gl/Gx2SYn. To learn other workflows see this article: https://goo.gl/EzSuwQ.



# Other proposed tutorials



## Structured workflow

(proposed by @rutujaCT)

https://goo.gl/syFKmT



## Tidy data with tidyr

(proposed by @djj4tree )

- https://goo.gl/2vjJFn
- https://goo.gl/NrFmik

## Good coding practices

(proposed by @djj4tree)

- [The tidyverse style guide](http://style.tidyverse.org/)
- [R for Data Science](http://r4ds.had.co.nz/)

CLASSICS (paid)

- [The Pragmatic Programmer](https://pragprog.com/book/tpp/the-pragmatic-programmer)
- [Code Complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)




